### ISSUE TITLE
Compilation on macos m1

### ISSUE THREAD

**Issue by jacobaraujo7** [leehack/flutter_golang_ffi_example#1]
First of all, thank you very much for the wonderful article.

I downloaded the repository and ran the example on macos and it worked!
The problem was when I tried to rebuild the dylib and from then on the lib was no longer found nor its reference.
Did you compile it in any different way?
I'm trying to cross over from macos with Apple Silicom M1

CC="clang -arch x86_64" \
	CGO_ENABLED=1 \
	GOARCH=amd64 \
	GOOS=darwin \
	go build -trimpath -buildmode=c-shared -o libsum.dylib ../src/sum.go
	
	
	Thank you!

**Comment by leehack** [comment]
@jacobaraujo7 
Would you try `make macos`? I haven't written about it in the article but the Makefile should have the script for macos build.
Let me know if that doesn't work. I can try myself later.

**Comment by jacobaraujo7** [comment]
Thanks for the answer.
I was trying to run the plugin on platforms other than Android and iOS. So I tried windows and linux and it worked like a dream.
On macos, there was already a compiled libsum.dylib that also works.
I tried to add more code to go.sum but flutter cannot call the functions.
So I tried going back to the original lib from the repository and it worked.
I removed the code I added and tried building go again, and that didn't work.
That's why I wanted to know if you used any specific flag to compile, or if you did this on another operating system other than M1.
Thanks again for your attention.

**Comment by leehack** [comment]
@jacobaraujo7 How did you build? using `make macos`?
As you can see in the Makefile: https://github.com/leehack/flutter_golang_ffi_example/blob/main/src/Makefile#L83

It builds for both platform silicon and intel. The make command should build it and copy it into the right folder.

**Comment by jacobaraujo7** [comment]
Yes! Work on!
Thank you
